# Generated by Django 5.2.7 on 2025-10-27 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0004_order_payment_method_recentlyvieweditem_and_more"),
        ("products", "0003_stockadjustmentreason_alter_stockmovement_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.AlterField(
            model_name="savedforlateritem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_for_later_by",
                to="products.productvariant",
            ),
        ),
        migrations.DeleteModel(
            name="RecentlyViewedItem",
        ),
    ]
