# Generated by Django 5.2.7 on 2025-10-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0006_order_payment_method_recentlyvieweditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
