# Generated by Django 5.2.7 on 2025-10-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0007_order_paid_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PROCESSING", "Processing"),
                    ("PAID", "Paid"),
                    ("SHIPPED", "Shipped"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING_PAYMENT",
                max_length=32,
            ),
        ),
    ]
