# Generated by Django 5.2.7 on 2025-10-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0009_refund_config_and_order_refund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderrefund",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="refundconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
