# Generated by Django 5.2.7 on 2025-11-02 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0013_alter_wishlistitem_unique_together_and_more"),
        ("products", "0008_trendingdeal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recentlyvieweditem",
            unique_together={("user", "variant")},
        ),
        migrations.AddField(
            model_name="recentlyvieweditem",
            name="session_key",
            field=models.CharField(
                blank=True,
                help_text="Session key for anonymous users",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recentlyvieweditem",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recently_viewed_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recentlyvieweditem",
            unique_together={("session_key", "variant"), ("user", "variant")},
        ),
        migrations.AddConstraint(
            model_name="recentlyvieweditem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    ("session_key__isnull", False),
                    _connector="OR",
                ),
                name="recently_viewed_user_or_session",
            ),
        ),
    ]
