# Generated by Django 5.2.3 on 2025-11-09 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0014_alter_recentlyvieweditem_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff user that created this order manually.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="management_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="offline_reference",
            field=models.CharField(
                blank=True,
                help_text="Reference number for offline invoices or POS systems.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_source",
            field=models.CharField(
                choices=[("ONLINE", "Online"), ("OFFLINE", "Offline / Point of Sale")],
                default="ONLINE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_label_required",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to skip automatic shipment creation (useful for offline pickup orders).",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("RAZORPAY", "Razorpay"),
                    ("COD", "Cash on Delivery"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                ],
                default="RAZORPAY",
                max_length=20,
            ),
        ),
    ]
