# Generated by Django 5.2.3 on 2025-11-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0016_giftcard_giftcardtransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g., USD, EUR)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "rate_to_inr",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Exchange rate: 1 unit of this currency = this many INR",
                        max_digits=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Currency Exchange Rate",
                "verbose_name_plural": "Currency Exchange Rates",
                "ordering": ["currency_code"],
            },
        ),
    ]
