# Generated by Django 5.2.7 on 2025-11-10 17:51

from django.db import migrations, models
import secrets
import string


def generate_order_number():
    """Generate a secure order number in format ORD-XXXX-XXXX"""
    chars = string.ascii_uppercase + string.digits
    part1 = ''.join(secrets.choice(chars) for _ in range(4))
    part2 = ''.join(secrets.choice(chars) for _ in range(4))
    return f"ORD-{part1}-{part2}"


def populate_order_numbers(apps, schema_editor):
    Order = apps.get_model('commerce', 'Order')
    # Use a set to track numbers generated in this run to avoid collisions before DB check
    existing_numbers = set(Order.objects.exclude(order_number='').values_list('order_number', flat=True))
    
    orders_to_update = []
    # Find all orders that have a blank order_number
    for order in Order.objects.filter(order_number=''):
        # Generate unique order number
        order_num = generate_order_number()
        while order_num in existing_numbers or Order.objects.filter(order_number=order_num).exists():
            order_num = generate_order_number()
        
        order.order_number = order_num
        orders_to_update.append(order)
        existing_numbers.add(order_num)

    # Bulk update for efficiency
    if orders_to_update:
        Order.objects.bulk_update(orders_to_update, ['order_number'])


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0017_currencyexchangerate"),
    ]
    
    # This migration is split into three parts to handle adding a unique field
    # to a table that already has data.
    # 1. Add the field as non-unique.
    # 2. Populate the field with unique data.
    # 3. Alter the field to enforce uniqueness at the database level.

    operations = [
        # Step 1: Add the field, but without the unique constraint for now.
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True,
                help_text="Unique order number in format ORD-XXXX-XXXX (auto-generated)",
                max_length=20,
            ),
        ),
        
        # Step 2: Populate the new field with unique values for existing rows.
        migrations.RunPython(populate_order_numbers, migrations.RunPython.noop),
        
        # Step 3: Now that all rows have data, add the unique constraint.
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True,
                help_text="Unique order number in format ORD-XXXX-XXXX (auto-generated)",
                max_length=20,
                unique=True,
            ),
        ),
    ]
