# Generated by Django 5.2.7 on 2025-11-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0018_add_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="session_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
