# Generated by Django 5.2.7 on 2025-10-25 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAdjustmentReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text="Legacy reason or additional details.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.stockadjustmentreason",
            ),
        ),
    ]
