# Generated by Django 4.2.4 on 2025-10-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariant_reserved_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, help_text='Check if this product has multiple variants like size or color.'),
        ),
    ]
