# Generated by Django 5.2.3 on 2025-11-01 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_has_variants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="review_images/"),
        ),
        migrations.AddField(
            model_name="productreview",
            name="user_name",
            field=models.CharField(
                blank=True, help_text="Required for guest reviews", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
