# Generated by Django 5.2.7 on 2025-11-02 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productreview_image_productreview_user_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendingDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deal_type",
                    models.CharField(
                        choices=[
                            ("PERCENT_OFF", "Percentage Off"),
                            ("CASHBACK", "Cashback"),
                            ("BOGO", "Buy 1 Get 1"),
                            ("FLAT_DISCOUNT", "Flat Discount"),
                            ("NEW", "New Arrival"),
                            ("FLASH", "Flash Sale"),
                            ("DROP", "New Drop"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label like 'NEW • Madara LED Box at ₹699'",
                        max_length=100,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage discount (e.g., 20.00 for 20%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "cashback_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cashback amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "flat_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Flat discount amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which deals appear (lower numbers first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this deal is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to category if deal applies to entire category",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trending_deals",
                        to="products.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to specific product",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trending_deals",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trending Deal",
                "verbose_name_plural": "Trending Deals",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
