# Generated by Django 5.2.3 on 2025-11-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_trendingdeal"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendingdeal",
            name="ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional end datetime. Leave blank for open-ended deals.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trendingdeal",
            name="starts_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Go-live datetime for this deal. Leave blank to activate immediately.",
                null=True,
            ),
        ),
    ]
