# Generated by Django 5.2.7 on 2025-10-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_badge_referralcode_referral_userbadge"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="loyalty_tier",
            field=models.CharField(default="FAN", max_length=20),
        ),
    ]
