# Generated by Django 5.2.3 on 2025-11-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_customuser_full_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "referrer_points",
                    models.IntegerField(
                        default=100,
                        help_text="Points awarded to the referrer when someone signs up using their code",
                    ),
                ),
                (
                    "referred_points",
                    models.IntegerField(
                        default=50,
                        help_text="Points awarded to the new user when they sign up using a referral code",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="loyaltyconfig",
            name="points_to_wallet_ratio",
            field=models.DecimalField(
                decimal_places=4,
                default=100.0,
                help_text="How many loyalty points = 1 unit of wallet currency (e.g., 100 points = ₹1)",
                max_digits=10,
            ),
        ),
    ]
