# Generated by Django 5.2.7 on 2025-11-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_useraddress"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailReminderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Enable/disable email reminders"
                    ),
                ),
                (
                    "cart_reminder_days",
                    models.IntegerField(
                        default=1,
                        help_text="Days after cart abandonment to send first reminder",
                    ),
                ),
                (
                    "cart_reminder_frequency",
                    models.IntegerField(
                        default=3, help_text="Days between cart reminder emails"
                    ),
                ),
                (
                    "wishlist_reminder_days",
                    models.IntegerField(
                        default=7,
                        help_text="Days after adding to wishlist to send first reminder",
                    ),
                ),
                (
                    "wishlist_reminder_frequency",
                    models.IntegerField(
                        default=7, help_text="Days between wishlist reminder emails"
                    ),
                ),
                (
                    "max_cart_reminders",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum number of cart reminder emails to send",
                    ),
                ),
                (
                    "max_wishlist_reminders",
                    models.IntegerField(
                        default=2,
                        help_text="Maximum number of wishlist reminder emails to send",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Reminder Configuration",
                "verbose_name_plural": "Email Reminder Configurations",
            },
        ),
    ]
